use crate::tools::ToolRegistry;

pub(crate) fn register_openmedia_tools(registry: &ToolRegistry) {
    // ── OpenMedia native tools ────────────────────────────────────────────────
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaModelDownloadTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaRasterizeSvgTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaDiagramGenerateMermaidTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaHtmlToImageTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaCreateSvgTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaCreateChartTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaCreateIconTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaAnimateSvgTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaAnimateCreateTimelineTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaAnimateMorphPathsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaAnimateGenerateSpinnerTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaAnimateFromLottieTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaAnimateToLottieTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImageApplyFilterTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImageResizeTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImageCropTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImageTransformTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImageConvertTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImageBatchProcessTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoCreateTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoPreviewTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoCreateSlideshowTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoAddTransitionTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoAddAudioTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoFromTemplateTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoExtractFramesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaVideoTrimTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaTemplateCreateTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaTemplateReadTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaTemplateUpdateTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaTemplateDeleteTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImproveScoreImageTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImproveRefinePromptTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImproveAutoRefineTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImproveFeedbackTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaImproveQualityReportTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::openmedia::OpenMediaPingTool,
    ));
}

pub(crate) fn register_opendoc_tools(registry: &ToolRegistry) {
    // ── Opendoc Native Tools ──────────────────────────────────────────────────
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocOpenDocumentTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocReadDocumentTextTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocSearchDocumentTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocReplaceTextTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocDiffDocumentsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocDiffDocumentsVisualTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocChunkForEmbeddingTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocFillTemplateTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocValidateDocumentTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocValidatePdfAComplianceTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocExtractStructuredMetadataTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocConvertTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocExtractImagesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocSplitPdfTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocCreateHtmlTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocBatchConvertTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocCreateDocxTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocDocxAddParagraphTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocDocxAddTableTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocDocxAddImageTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocCreatePptxTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocPptxAddSlideTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocCreateXlsxTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocEditXlsxTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocCreatePdfTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocCreateFormattedPdfTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocMergePdfsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocExtractPdfTextTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocListPdfFieldsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocFillPdfFormTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocFindTablesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocAnalyzeDocumentComplexityTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocOcrDocumentTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocCheckOcrAvailableTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::opendoc::OpendocExtractArchiveDigestTool,
    ));
}

