use crate::tools::ToolRegistry;

pub(crate) fn register_sequential_thinking_tools(registry: &ToolRegistry) {
    // ── Sequential Thinking tools (native, ported from MCP) ──────
    registry.register(std::sync::Arc::new(
        crate::tools::sequential_thinking::SequentialThinkingTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::sequential_thinking::AnalyzeGraphTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::sequential_thinking::ExportSessionTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::sequential_thinking::SummarizeReasoningTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::sequential_thinking::TemplatesTool,
    ));
}

pub(crate) fn register_headroom_tools(registry: &ToolRegistry) {
    // ── CCR / Headroom tools (native, ported from MCP) ───────────
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::ScopeContextTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::CompressContentTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::RetrieveOriginalTool,
    ));
    registry.register(std::sync::Arc::new(crate::tools::headroom::PingTool));
    registry.register(std::sync::Arc::new(crate::tools::headroom::ServerInfoTool));
    registry.register(std::sync::Arc::new(crate::tools::headroom::CountTokensTool));
    registry.register(std::sync::Arc::new(crate::tools::headroom::CacheStatsTool));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::HeadroomStatsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::HeadroomUsageTool,
    ));
    registry.register(std::sync::Arc::new(crate::tools::headroom::ClearCacheTool));
    registry.register(std::sync::Arc::new(crate::tools::headroom::SearchCacheTool));
    registry.register(std::sync::Arc::new(crate::tools::headroom::CacheAlignTool));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::CompressSchemaTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::CompressFileTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::CompressDiffTool,
    ));
    registry.register(std::sync::Arc::new(crate::tools::headroom::ExportCacheTool));
    registry.register(std::sync::Arc::new(crate::tools::headroom::ImportCacheTool));
    registry.register(std::sync::Arc::new(crate::tools::headroom::CompressUrlTool));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::RunAndCompressTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::CompressDirectoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::headroom::SummarizeCodebaseTool,
    ));
}

pub(crate) fn register_graph_memory_tools(registry: &ToolRegistry) {
    // ── Graph Memory tools (native, ported from memory_rs MCP) ─────────────
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::CreateEntitiesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::CreateRelationsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::AddObservationsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::DeleteEntitiesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::DeleteObservationsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::DeleteRelationsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::ReadGraphTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::SearchNodesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::OpenNodesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::CreateDatabaseBranchTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::CommitDatabaseBranchTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::graph_memory::RollbackDatabaseBranchTool,
    ));
}

pub(crate) fn register_memory_extra_tools(registry: &ToolRegistry) {
    // ── Graph Memory Extra tools (ported from openmemory_rs MCP) ──────────
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::SetWorkingMemoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::GetWorkingMemoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::EvictExpiredWorkingMemoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::PromoteWorkingMemoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::LogExecutionEpisodeTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::LogReflectionTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::RetrieveEpisodicReflectionsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::RecordToolPerformanceTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::QueryToolPerformanceTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::StoreSharedTeamMemoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::RetrieveSharedTeamMemoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::SearchTextTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::HybridSearchTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::InvalidateFactTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::ForgetMemoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::QueryFactHistoryTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::QueryAsOfTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::SmartStoreTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::ExtractAndStoreFactsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::ProactiveRecallTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::CompressContextTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::MemoryStatsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::LogRepositoryEvolutionTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::QueryRepositoryEvolutionTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::TraverseGraphTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::FindPathTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::AnalyzeGraphCommunitiesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::DetectAndResolveConflictsTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::CompactMemoriesTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::IndexCodebaseTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::QueryCodeGraphTool,
    ));
    registry.register(std::sync::Arc::new(
        crate::tools::memory_extra::AnalyzeCodeImpactTool,
    ));
}
