//! Curated static specifications and routing metadata for native tools.

use super::metadata::{normalize_tool_name, ToolRisk, ToolSpec};

pub type StaticToolDef = ToolSpec;

pub static STATIC_TOOL_DEFS: &[StaticToolDef] = &[
    StaticToolDef {
        name: "cargo_manager",
        presentation_name: "Cargo Manager",
        domain: "code",
        risk: ToolRisk::Medium,
        packs: &["repo_read", "local_exec"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "cargo test",
            "cargo check",
            "cargo build",
            "clippy",
            "rust tests",
        ],
        examples: &["Run cargo test --lib", "Run cargo check after Rust edits"],
        when_to_use: "Use for Rust cargo build, check, test, clippy, and compiler-fix workflows.",
        when_not_to_use: "Avoid when only reading files or searching source text.",
    },
    StaticToolDef {
        name: "exec_command",
        presentation_name: "Bash",
        domain: "shell",
        risk: ToolRisk::High,
        packs: &["local_exec"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(180),
        aliases: &["shell command", "terminal", "bash", "run command"],
        examples: &[
            "Run ls to inspect generated files",
            "Run a safe project-local command",
        ],
        when_to_use: "Use for shell commands that cannot be handled by a safer native tool.",
        when_not_to_use: "Avoid for file reads, code search, or destructive commands without approval.",
    },
    StaticToolDef {
        name: "read_file",
        presentation_name: "Read",
        domain: "filesystem",
        risk: ToolRisk::Low,
        packs: &["repo_read"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["open file", "inspect file", "view file"],
        examples: &["Read src/main.rs before editing", "Inspect a config file"],
        when_to_use: "Use to inspect known text files before editing or explaining code.",
        when_not_to_use: "Avoid for broad searches; use grep or find tools instead.",
    },
    StaticToolDef {
        name: "list_dir",
        presentation_name: "List Dir",
        domain: "filesystem",
        risk: ToolRisk::Low,
        packs: &["repo_read"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["list directory", "directory listing", "show directory"],
        examples: &["List a source directory", "Inspect a repository folder"],
        when_to_use: "Use to inspect the entries and basic metadata of a project-local directory.",
        when_not_to_use: "Avoid for recursive content search; use grep_search or find_files instead.",
    },
    StaticToolDef {
        name: "code_outline",
        presentation_name: "Code Outline",
        domain: "code",
        risk: ToolRisk::Low,
        packs: &["repo_read"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["outline code", "inspect structure", "list symbols"],
        examples: &["Summarize a source file's definitions", "Inspect a module outline"],
        when_to_use: "Use to inspect source structure without reading an entire file.",
        when_not_to_use: "Avoid when exact implementation details or arbitrary text matches are needed.",
    },
    StaticToolDef {
        name: "proactive_recall",
        presentation_name: "Proactive Recall",
        domain: "memory",
        risk: ToolRisk::Low,
        packs: &["memory"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["recall relevant context", "memory context"],
        examples: &["Recall memories relevant to the current task"],
        when_to_use: "Use to retrieve relevant context across semantic, graph, and episodic memory layers.",
        when_not_to_use: "Avoid when the user asks to store, update, or delete a memory.",
    },
    StaticToolDef {
        name: "recall_memory",
        presentation_name: "Recall Memory",
        domain: "memory",
        risk: ToolRisk::Low,
        packs: &["memory"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["search memories", "retrieve memory", "remember"],
        examples: &["Recall a stored workflow or fact"],
        when_to_use: "Use to search durable cognitive memory for relevant facts, guidelines, or code patterns.",
        when_not_to_use: "Avoid for graph-only queries or when no durable memory lookup is needed.",
    },
    StaticToolDef {
        name: "read_graph",
        presentation_name: "Read Graph",
        domain: "memory",
        risk: ToolRisk::Low,
        packs: &["memory"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["read knowledge graph", "list graph"],
        examples: &["Read the scoped knowledge graph"],
        when_to_use: "Use to inspect all graph entities and relations within the requested memory scope.",
        when_not_to_use: "Avoid when a targeted node lookup or text-memory search is sufficient.",
    },
    StaticToolDef {
        name: "open_nodes",
        presentation_name: "Open Nodes",
        domain: "memory",
        risk: ToolRisk::Low,
        packs: &["memory"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["open graph nodes", "read graph nodes"],
        examples: &["Open named entities from the knowledge graph"],
        when_to_use: "Use to retrieve selected knowledge-graph entities by name.",
        when_not_to_use: "Avoid when a full graph read or semantic memory search is more appropriate.",
    },
    StaticToolDef {
        name: "smart_store",
        presentation_name: "Smart Store",
        domain: "memory",
        risk: ToolRisk::Low,
        packs: &["memory"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["merge memory", "store memory intelligently"],
        examples: &["Store a deduplicated fact or graph relation"],
        when_to_use: "Use to add or merge a durable fact or graph relation with memory-layer deduplication.",
        when_not_to_use: "Avoid for transient notes or when the user asks to delete or invalidate memory.",
    },
    StaticToolDef {
        name: "retrieve_original",
        presentation_name: "Retrieve Original",
        domain: "context",
        risk: ToolRisk::High,
        packs: &["core", "web_research"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["retrieve full output", "read original content"],
        examples: &["Retrieve the full content for a CCR reference"],
        when_to_use: "Use to retrieve uncompressed tool output or a validated file path when the compact result is insufficient.",
        when_not_to_use: "Avoid for sensitive files or when the existing compact output answers the question.",
    },
    StaticToolDef {
        name: "write_file",
        presentation_name: "Write",
        domain: "filesystem",
        risk: ToolRisk::High,
        packs: &["repo_write"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[],
        examples: &["Write a small project file", "Create or replace a local text file"],
        when_to_use: "Use to create or replace a project-local text file when a targeted patch is not appropriate.",
        when_not_to_use: "Avoid rewriting an existing file when patch_file or replace_lines can make a smaller edit.",
    },
    StaticToolDef {
        name: "patch_file",
        presentation_name: "Edit",
        domain: "filesystem",
        risk: ToolRisk::High,
        packs: &["repo_write"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[],
        examples: &["Apply a focused unified diff", "Make a targeted source edit"],
        when_to_use: "Use for targeted project-local edits represented as a unified diff.",
        when_not_to_use: "Avoid for creating a new file or replacing an exact line range; use write_file or replace_lines.",
    },
    StaticToolDef {
        name: "replace_lines",
        presentation_name: "Edit",
        domain: "filesystem",
        risk: ToolRisk::High,
        packs: &["repo_write"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[],
        examples: &["Replace a known line range", "Make a surgical text edit"],
        when_to_use: "Use to replace an exact inclusive line range in a project-local text file.",
        when_not_to_use: "Avoid when a unified diff is clearer or when the target file does not already exist.",
    },
    StaticToolDef {
        name: "grep_search",
        presentation_name: "Grep Search",
        domain: "code",
        risk: ToolRisk::Low,
        packs: &["repo_read"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["search code", "find text", "ripgrep"],
        examples: &["Find all uses of a function", "Search for a symbol in src"],
        when_to_use: "Use to find symbols, text, TODOs, and call sites across a project.",
        when_not_to_use: "Avoid when the exact file is already known and only needs reading.",
    },
    StaticToolDef {
        name: "web_fetch",
        presentation_name: "Web Fetch",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: None,
        aliases: &["fetch url", "read webpage", "download page"],
        examples: &["Fetch a documentation URL", "Read one webpage"],
        when_to_use: "Use to read a specific URL supplied by the user or found by search.",
        when_not_to_use: "Avoid for open-ended research; search first.",
    },
    StaticToolDef {
        name: "web_search",
        presentation_name: "Web Search",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: None,
        aliases: &["internet search", "search web", "lookup online"],
        examples: &[
            "Search current public documentation",
            "Look up recent release info",
        ],
        when_to_use: "Use when current or external web information is required.",
        when_not_to_use: "Avoid when the answer is fully available from local project files.",
    },
    StaticToolDef {
        name: "searchxyz_browser_search",
        presentation_name: "Searchxyz Browser Search",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: Some(600),
        aliases: &["searchxyz browser", "browser web search"],
        examples: &["Search the web through the browser fallback"],
        when_to_use: "Use for browser-backed web discovery when direct search backends are unavailable or explicit engine control is needed.",
        when_not_to_use: "Avoid for local-only questions or when a direct URL can be fetched more cheaply.",
    },
    StaticToolDef {
        name: "searchxyz_search_web",
        presentation_name: "Searchxyz Search Web",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: None,
        aliases: &["searchxyz search", "native web search"],
        examples: &["Search public web sources with SearchXyz"],
        when_to_use: "Use for keyless or provider-free public web search through the native SearchXyz dispatcher.",
        when_not_to_use: "Avoid when only local repository context is required.",
    },
    StaticToolDef {
        name: "searchxyz_read_url",
        presentation_name: "Searchxyz Read Url",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: None,
        aliases: &["searchxyz url", "searchxyz webpage"],
        examples: &["Read a specific webpage through SearchXyz"],
        when_to_use: "Use to fetch and extract one known URL, optionally with rendering or persistence controls.",
        when_not_to_use: "Avoid for open-ended discovery; use a web search tool first.",
    },
    StaticToolDef {
        name: "searchxyz_search_and_read",
        presentation_name: "Searchxyz Search And Read",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: None,
        aliases: &["search and read", "searchxyz combined research"],
        examples: &["Search for and read relevant web pages"],
        when_to_use: "Use when a task needs both web discovery and extraction of the most relevant result pages.",
        when_not_to_use: "Avoid when the user already supplied one exact URL.",
    },
    StaticToolDef {
        name: "searchxyz_deep_research",
        presentation_name: "Searchxyz Deep Research",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: None,
        aliases: &["deep web research", "searchxyz research"],
        examples: &["Run a multi-query web research task"],
        when_to_use: "Use for iterative multi-query web research and a compiled research report.",
        when_not_to_use: "Avoid for a single-page lookup or a local-code question.",
    },
    StaticToolDef {
        name: "searchxyz_read_github_repo",
        presentation_name: "Searchxyz Read Github Repo",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: None,
        aliases: &["github repository research", "searchxyz github repo"],
        examples: &["Read and index a public GitHub repository"],
        when_to_use: "Use to inspect and index a public GitHub repository with bounded file and byte limits.",
        when_not_to_use: "Avoid when local repository files are already available or remote access is not needed.",
    },
    StaticToolDef {
        name: "delegate_task",
        presentation_name: "Delegate Task",
        domain: "subagent",
        risk: ToolRisk::Low,
        packs: &["subagent"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(600),
        aliases: &["subagent", "delegate", "specialist agent"],
        examples: &[
            "Ask a reviewer subagent to inspect changes",
            "Route image analysis to a vision subagent",
        ],
        when_to_use: "Use for independent specialist work, reviews, research, or multimodal routing.",
        when_not_to_use: "Avoid for simple direct actions the orchestrator can complete itself.",
    },
    StaticToolDef {
        name: "parallel_research",
        presentation_name: "Parallel Research",
        domain: "subagent",
        risk: ToolRisk::Medium,
        packs: &["subagent"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(600),
        aliases: &["parallel subagent research"],
        examples: &["Run independent repository or web research tasks in parallel"],
        when_to_use: "Use when multiple independent research tasks can be delegated concurrently to read-only subagents.",
        when_not_to_use: "Avoid when tasks depend on one another or require filesystem writes.",
    },
    StaticToolDef {
        name: "evaluator_optimizer_loop",
        presentation_name: "Evaluator Optimizer Loop",
        domain: "subagent",
        risk: ToolRisk::Medium,
        packs: &["subagent"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(600),
        aliases: &["subagent review loop"],
        examples: &["Iteratively generate and review a subagent draft"],
        when_to_use: "Use when a draft needs repeated specialist generation and evaluator feedback.",
        when_not_to_use: "Avoid for a simple one-pass delegation or unrelated independent tasks.",
    },
    StaticToolDef {
        name: "create_subagent",
        presentation_name: "Create Subagent",
        domain: "subagent",
        risk: ToolRisk::High,
        packs: &["subagent"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["create subagent profile"],
        examples: &["Create a reusable specialized subagent profile"],
        when_to_use: "Use to create and persist a custom subagent profile for future delegated work.",
        when_not_to_use: "Avoid when an existing profile already covers the task.",
    },
    StaticToolDef {
        name: "delete_subagent",
        presentation_name: "Delete Subagent",
        domain: "subagent",
        risk: ToolRisk::High,
        packs: &["subagent"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["delete subagent profile"],
        examples: &["Delete an unused custom subagent profile"],
        when_to_use: "Use to remove a custom subagent profile when explicit cleanup is requested.",
        when_not_to_use: "Avoid for protected default profiles or when the profile may still be needed.",
    },
    StaticToolDef {
        name: "update_subagent_settings",
        presentation_name: "Update Subagent Settings",
        domain: "subagent",
        risk: ToolRisk::High,
        packs: &["subagent"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["update subagent profile"],
        examples: &["Update a subagent model or fallback list"],
        when_to_use: "Use to change the persisted model and fallback settings of an existing subagent profile.",
        when_not_to_use: "Avoid when only a one-off model override is needed for the current delegation.",
    },
    StaticToolDef {
        name: "optimize_subagent",
        presentation_name: "Optimize Subagent",
        domain: "subagent",
        risk: ToolRisk::High,
        packs: &["subagent"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["optimize subagent profile"],
        examples: &["Improve a subagent prompt from feedback logs"],
        when_to_use: "Use to revise and persist a subagent system prompt based on concrete feedback.",
        when_not_to_use: "Avoid without a specific failure, feedback signal, or profile target.",
    },
    StaticToolDef {
        name: "git_manager",
        presentation_name: "Git Manager",
        domain: "git",
        risk: ToolRisk::Low,
        packs: &["repo_read"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["git status", "git diff", "git commit", "git log"],
        examples: &["Check git status", "Review a diff before commit"],
        when_to_use: "Use for git status, diffs, commit history, and repository state checks.",
        when_not_to_use: "Avoid for GitHub API operations; use GitHub tools for remote provider actions.",
    },
    StaticToolDef {
        name: "desktop_notify",
        presentation_name: "Desktop Notify",
        domain: "self_management",
        risk: ToolRisk::High,
        packs: &["core", "cron"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: Some(10),
        aliases: &["desktop notification", "notify desktop", "show notification"],
        examples: &["Show a desktop reminder", "Notify me when the task finishes"],
        when_to_use: "Use for local desktop notifications. Prefer this over shell notify-send or system crontab commands.",
        when_not_to_use: "Avoid for Telegram, Discord, or email notifications; use the channel-specific tools.",
    },
    StaticToolDef {
        name: "request_tool_scope",
        presentation_name: "Request Tool Scope",
        domain: "self_management",
        risk: ToolRisk::Low,
        packs: &["core"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["need more tools", "missing tool", "expand tool scope"],
        examples: &[
            "Ask for grep_search when the current turn only has core tools",
            "Request web tools when the user clarifies they need live research",
        ],
        when_to_use: "Use when the current scoped tool set is missing the exact tool or domain required to complete the request.",
        when_not_to_use: "Avoid when the required tool is already visible or the answer can be completed directly.",
    },
    StaticToolDef {
        name: "tool_catalog",
        presentation_name: "Tool Catalog",
        domain: "self_management",
        risk: ToolRisk::Low,
        packs: &["core"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["list tools", "tool help", "available tools"],
        examples: &[
            "List tools for a website research task",
            "Explain why tools were hidden",
        ],
        when_to_use: "Use to inspect available tools, routing decisions, and hidden tool reasons.",
        when_not_to_use: "Avoid when the correct tool is already obvious and exposed.",
    },
    StaticToolDef {
        name: "openz_inventory",
        presentation_name: "Openz Inventory",
        domain: "self_management",
        risk: ToolRisk::Low,
        packs: &["core"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["features", "capabilities", "what can you do", "inventory"],
        examples: &[
            "Answer exactly what OpenZ features and tools are currently registered",
            "Compare claimed features against live tool inventory",
        ],
        when_to_use: "Use before answering questions about OpenZ's exact features, commands, channels, subagents, and registered tools.",
        when_not_to_use: "Avoid guessing feature counts from memory when live registry data is available.",
    },
    StaticToolDef {
        name: "manage_servers",
        presentation_name: "Manage Servers",
        domain: "self_management",
        risk: ToolRisk::Low,
        packs: &[],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "stop server",
            "list servers",
            "dev server",
            "background process",
        ],
        examples: &[
            "List active dev servers after launching npm run dev",
            "Stop all OpenZ-launched servers when the task is done",
        ],
        when_to_use: "Use to inspect or stop dev servers/background processes launched by OpenZ; call it automatically when cleanup is needed.",
        when_not_to_use: "Avoid shell pkill guesses for servers OpenZ registered itself.",
    },
    StaticToolDef {
        name: "device_inventory",
        presentation_name: "Device Inventory",
        domain: "self_management",
        risk: ToolRisk::High,
        packs: &[],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "device apps",
            "app inventory",
            "local capability registry",
            "known viewers",
        ],
        examples: &[
            "Suggest an image viewer for a generated PNG",
            "Record that Firefox successfully opened an image",
        ],
        when_to_use: "Use before opening/showing/playing local files so OpenZ reuses known apps, viewers, editors, file paths, and device capabilities for this computer.",
        when_not_to_use: "Avoid storing secrets, API keys, arbitrary shell pipelines, or information unrelated to local device capability.",
    },
    StaticToolDef {
        name: "schedule_job",
        presentation_name: "Schedule Job",
        domain: "self_management",
        risk: ToolRisk::High,
        packs: &["cron"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "cron",
            "cron job",
            "schedule job",
            "timer",
            "run later",
            "automated task",
        ],
        examples: &[
            "Schedule a prompt to run every 5 minutes",
            "Create a timer for an automated reminder or action",
        ],
        when_to_use: "Use to schedule automated prompts, reminders, timers, and cron-style future tasks from chat.",
        when_not_to_use: "Avoid shell cron, systemd-run, or sleep loops unless the native scheduler cannot express the request.",
    },
    StaticToolDef {
        name: "list_jobs",
        presentation_name: "List Jobs",
        domain: "self_management",
        risk: ToolRisk::Low,
        packs: &["cron"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["list cron jobs", "scheduled jobs", "timers", "cron status"],
        examples: &["List active scheduled cron jobs", "Check timer status"],
        when_to_use: "Use to inspect OpenZ-managed scheduled jobs before reporting cron/timer status.",
        when_not_to_use: "Avoid shell crontab or systemctl listing for jobs created by OpenZ.",
    },
    StaticToolDef {
        name: "remove_job",
        presentation_name: "Remove Job",
        domain: "self_management",
        risk: ToolRisk::High,
        packs: &["cron"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "remove cron job",
            "delete scheduled job",
            "cancel timer",
            "stop scheduled job",
        ],
        examples: &[
            "Cancel a scheduled job by id",
            "Remove a timer after it has fired",
        ],
        when_to_use: "Use to cancel or delete OpenZ-managed scheduled jobs by id when cleanup is requested.",
        when_not_to_use: "Avoid shell systemctl, crontab editing, or pkill guesses for OpenZ scheduler cleanup.",
    },
    StaticToolDef {
        name: "pause_job",
        presentation_name: "Pause Job",
        domain: "cron",
        risk: ToolRisk::High,
        packs: &["cron"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["pause cron job", "disable scheduled job", "stop timer"],
        examples: &["Pause a recurring cron job without deleting it"],
        when_to_use: "Use to pause or disable an OpenZ-managed scheduled job without deleting its inventory or run logs.",
        when_not_to_use: "Avoid shell crontab, systemctl, or filesystem guessing for OpenZ-managed cron jobs.",
    },
    StaticToolDef {
        name: "resume_job",
        presentation_name: "Resume Job",
        domain: "cron",
        risk: ToolRisk::High,
        packs: &["cron"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["resume cron job", "enable scheduled job", "restart timer"],
        examples: &["Resume a paused OpenZ cron job"],
        when_to_use: "Use to resume or enable a paused OpenZ-managed scheduled job and let the scheduler recalculate its next run.",
        when_not_to_use: "Avoid shell crontab, systemctl, or filesystem guessing for OpenZ-managed cron jobs.",
    },
    StaticToolDef {
        name: "get_job",
        presentation_name: "Get Job",
        domain: "cron",
        risk: ToolRisk::Low,
        packs: &["cron"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &["get cron job", "cron job details", "scheduled job details"],
        examples: &["Show the inventory record for cron job daily"],
        when_to_use: "Use to inspect one OpenZ-managed scheduled job inventory record before reporting automation status.",
        when_not_to_use: "Avoid shell crontab, systemctl, or filesystem guessing for OpenZ-managed cron jobs.",
    },
    StaticToolDef {
        name: "get_job_logs",
        presentation_name: "Get Job Logs",
        domain: "cron",
        risk: ToolRisk::Low,
        packs: &["cron"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "cron logs",
            "job logs",
            "scheduled job history",
            "cron run history",
        ],
        examples: &["Show recent structured logs for cron job daily"],
        when_to_use: "Use to inspect structured run history for OpenZ-managed scheduled jobs before reporting cron automation status.",
        when_not_to_use: "Avoid shell crontab, systemctl, or filesystem guessing for OpenZ-managed cron jobs.",
    },
    StaticToolDef {
        name: "run_job_now",
        presentation_name: "Run Job Now",
        domain: "cron",
        risk: ToolRisk::High,
        packs: &["cron"],
        writes_disk: true,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "run cron job now",
            "trigger scheduled job",
            "manual cron run",
        ],
        examples: &["Run cron job daily immediately"],
        when_to_use: "Use to manually trigger an existing OpenZ-managed scheduled job immediately from its inventory id.",
        when_not_to_use: "Avoid shell crontab, systemctl, or filesystem guessing for OpenZ-managed cron jobs.",
    },
    StaticToolDef {
        name: "workflow_memory",
        presentation_name: "Workflow Memory",
        domain: "self_management",
        risk: ToolRisk::Low,
        packs: &[],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: None,
        aliases: &[
            "save workflow",
            "reuse workflow",
            "record run",
            "procedure memory",
        ],
        examples: &[
            "Save a repeated website/video generation procedure",
            "Record whether a reused workflow succeeded",
        ],
        when_to_use: "Use to save, search, or record reusable procedures after repeated successful tasks or tool-workaround discoveries.",
        when_not_to_use: "Avoid leaving repeated multi-step workflows only in chat history.",
    },
    StaticToolDef {
        name: "orchestrate_workflow",
        presentation_name: "Orchestrate Workflow",
        domain: "subagent",
        risk: ToolRisk::Low,
        packs: &["orchestrator"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(600),
        aliases: &[
            "multi-agent workflow",
            "orchestrator",
            "workflow runtime",
            "agent workflow",
        ],
        examples: &[
            "Plan a sequential research and review workflow",
            "Run a typed workflow across declared agents",
        ],
        when_to_use: "Use to run typed, observable multi-agent workflow specs through the native OpenZ orchestrator runtime.",
        when_not_to_use: "Avoid when a single direct tool call or one delegate_task invocation is enough.",
    },
    StaticToolDef {
        name: "html_to_video",
        presentation_name: "Html To Video",
        domain: "media",
        risk: ToolRisk::Low,
        packs: &["media"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(900),
        aliases: &["render video", "html video", "animation to mp4"],
        examples: &[
            "Render an HTML animation timeline to MP4",
            "Convert a page animation into a video file",
        ],
        when_to_use: "Use to render HTML/CSS animation timelines into video files via CDP.",
        when_not_to_use: "Avoid for programmatic video without HTML; use generate_video instead.",
    },
    StaticToolDef {
        name: "generate_video",
        presentation_name: "Generate Video",
        domain: "media",
        risk: ToolRisk::Low,
        packs: &["media"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(900),
        aliases: &["make video", "programmatic video", "wavyte video"],
        examples: &[
            "Generate a programmatic MP4 via the Wavyte API",
            "Produce a video artifact from code",
        ],
        when_to_use: "Use to generate videos from programmatic scene descriptions.",
        when_not_to_use: "Avoid when an HTML timeline already exists; html_to_video is cheaper.",
    },
    StaticToolDef {
        name: "crawl_website",
        presentation_name: "Crawl Website",
        domain: "web",
        risk: ToolRisk::Medium,
        packs: &["web_research"],
        writes_disk: false,
        uses_network: true,
        recommended_timeout_secs: Some(600),
        aliases: &["crawl site", "spider website", "multi-page scrape"],
        examples: &[
            "Crawl a documentation site for all pages",
            "Spider a domain and summarize its pages",
        ],
        when_to_use: "Use to fetch and analyze many pages of one website.",
        when_not_to_use: "Avoid for a single known URL; use web_fetch instead.",
    },
    StaticToolDef {
        name: "create_animated_svg",
        presentation_name: "Create Animated Svg",
        domain: "media",
        risk: ToolRisk::Medium,
        packs: &["media"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(300),
        aliases: &["animated svg", "svg animation"],
        examples: &[
            "Compile an animation timeline into an animated SVG",
            "Create an animated diagram",
        ],
        when_to_use: "Use to compile element/animation specs into a self-contained animated SVG.",
        when_not_to_use: "Avoid for static SVGs or raster image output.",
    },
    StaticToolDef {
        name: "generate_image",
        presentation_name: "Generate Image",
        domain: "media",
        risk: ToolRisk::Low,
        packs: &["media"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(300),
        aliases: &["make image", "render png", "html to image"],
        examples: &[
            "Render an HTML/CSS layout to PNG",
            "Generate a diagram image",
        ],
        when_to_use: "Use to render HTML/CSS/SVG specs into raster images.",
        when_not_to_use: "Avoid for vector output; use create_animated_svg or SVG tools.",
    },
    StaticToolDef {
        name: "render_mermaid",
        presentation_name: "Render Mermaid",
        domain: "media",
        risk: ToolRisk::Low,
        packs: &["media"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(300),
        aliases: &["mermaid diagram", "flowchart"],
        examples: &[
            "Render a Mermaid flowchart to an image",
            "Draw an architecture diagram",
        ],
        when_to_use: "Use to render Mermaid diagram definitions into visual artifacts.",
        when_not_to_use: "Avoid for hand-authored SVG; use SVG tools directly.",
    },
    StaticToolDef {
        name: "semantic_search",
        presentation_name: "Semantic Search",
        domain: "code",
        risk: ToolRisk::Low,
        packs: &["repo_read"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(300),
        aliases: &["vector search", "semantic code search", "embeddings search"],
        examples: &[
            "Find code by meaning across the repo",
            "Locate implementation similar to a description",
        ],
        when_to_use: "Use to search a repository by semantic similarity, including first-time indexing.",
        when_not_to_use: "Avoid for exact-text lookups; grep_search is faster and cheaper.",
    },
    StaticToolDef {
        name: "python_sandbox",
        presentation_name: "Python Sandbox",
        domain: "shell",
        risk: ToolRisk::Medium,
        packs: &["local_exec"],
        writes_disk: false,
        uses_network: false,
        recommended_timeout_secs: Some(180),
        aliases: &["run python", "python repl", "python script"],
        examples: &[
            "Run a short Python computation",
            "Process data with a Python snippet",
        ],
        when_to_use: "Use to execute isolated Python code for computation or data wrangling.",
        when_not_to_use: "Avoid for shell-native tasks; exec_command covers most workflows.",
    },
];

/// Names covered by the curated static tool definitions. Consumed by the
/// full-registry registration test to catch drift between the table and the
/// actual tool implementations (misnamed entries silently never apply).
pub fn static_tool_def_names() -> Vec<&'static str> {
    STATIC_TOOL_DEFS.iter().map(|def| def.name).collect()
}

/// Return one curated static tool specification by canonical name or alias.
pub fn tool_spec(name_or_alias: &str) -> Option<&'static ToolSpec> {
    let requested = normalize_tool_name(name_or_alias);
    STATIC_TOOL_DEFS.iter().find(|spec| {
        normalize_tool_name(spec.name) == requested
            || spec
                .aliases
                .iter()
                .any(|alias| normalize_tool_name(alias) == requested)
    })
}

/// Return all curated static tool specifications in registration-table order.
pub fn all_tool_specs() -> &'static [ToolSpec] {
    STATIC_TOOL_DEFS
}
